package org.siros.wwwallet.json

import android.net.Uri
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class DcApiRequests(
    val requests: List<DcApiRequest>,
)

@Serializable
data class DcApiRequest(
    val data: DcApiRequestData,
    val protocol: String,
)

@Serializable
data class DcApiRequestData(
    @SerialName("client_id")
    val clientId: String? = null,
    @SerialName("response_type")
    val responseType: String? = null,
    @SerialName("response_mode")
    val responseMode: String? = null,
    val nonce: String? = null,
    @SerialName("client_metadata")
    val clientMetadata: JsonElement? = null,
    val request: String? = null,
    @SerialName("transaction_data")
    val transactionData: JsonElement? = null,
    @SerialName("dcql_query")
    val dcqlQuery: JsonElement? = null,
    @SerialName("verifier_info")
    val verifierInfo: JsonElement? = null,
) {
    /**
     * Documentation:
     *
     * https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#appendix-A.2-6
     *
     * As per @smncd:
     *
     * Always Set
     *
     *  - request_id — UUID for request correlation (randomy generated by app, sent back to app by web frontend)
     *
     * Signed Request
     *
     *  Only the parameter above plus:
     *
     *      - request — JWT-encoded signed authorization request
     *      - client_id — Origin of requesting website (verifier)
     *
     * Unsigned Request
     *
     *  All of the above plus:
     *
     *      - response_type — Default: vp_token
     *      - response_mode — Default: dc_api
     *      - nonce — Optional, for replay protection
     *      - response_uri — verifier
     *      - state — Optional, for state tracking
     *      - client_metadata — JSON-stringified, defaults to {}
     *      - dcql_query — JSON-stringified, defaults to {}
     *      - transaction_data — JSON-stringified array (only if present)
     *
     *  Key point: Signed requests (JAR) return early with minimal parameters, while unsigned
     *  requests include full credential request details.
     *
     */
    fun addAsQuery(uri: Uri.Builder) {
        if (request != null) {
            uri
                .appendQueryParameter("clientId", clientId)
                .appendQueryParameter("request", request)
        } else {
            uri
                .appendQueryParameter("response_type", responseType)
                .appendQueryParameter("response_mode", responseMode)
                .appendQueryParameter("nonce", nonce)
                .appendQueryParameter("client_metadata", clientMetadata?.toString() ?: "{}")
                .appendQueryParameter("transaction_data", transactionData?.toString())
                .appendQueryParameter("dcql_query", dcqlQuery?.toString() ?: "{}")
                .appendQueryParameter("verifier_info", verifierInfo?.toString())
        }
    }
}
