name: Android Build and Publish

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on new tags (e.g., v1.0.0)
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger this workflow run manually?
        required: true
        default: Needing a new build.
        type: string
      tag:
        description: Which tag to build from?
        required: true
        default: v0.0.14
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      WWWALLET_ANDROID_APPLICATION_ID: ${{ vars.WWWALLET_ANDROID_APPLICATION_ID }}
      WWWALLET_ANDROID_KEY_ALIAS: ${{ secrets.WWWALLET_ANDROID_KEY_ALIAS }}
      WWWALLET_ANDROID_RELEASE_KEY_ALIAS: ${{ secrets.WWWALLET_ANDROID_RELEASE_KEY_ALIAS }}
      WWWALLET_ANDROID_KEY_PASSWORD: ${{ secrets.WWWALLET_ANDROID_KEY_PASSWORD }}
      WWWALLET_ANDROID_STORE_PASSWORD: ${{ secrets.WWWALLET_ANDROID_STORE_PASSWORD }}
      WWWALLET_ANDROID_STORE_B64: ${{ secrets.WWWALLET_ANDROID_STORE_B64 }}
      ANDROID_TARGET_SDK: ${{ vars.ANDROID_TARGET_SDK }}
      ANDROID_BUILD_TOOLS: ${{ vars.ANDROID_BUILD_TOOLS }}
      ANDROID_CMDLINE_TOOLS: ${{ vars.ANDROID_CMDLINE_TOOLS }}

    steps:
      - name: Update ubuntu
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      # https://github.com/android-actions/setup-android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: ${{ env.ANDROID_CMDLINE_TOOLS }}
          packages: 'tools platform-tools platforms;android-${{ env.ANDROID_TARGET_SDK }} build-tools;${{ env.ANDROID_BUILD_TOOLS }}'

      - name: Add build-tools to PATH
        run: echo "$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS}" >> $GITHUB_PATH

      - name: Code Style
        run: ./gradlew ktlintCheck

      - name: Test
        run: ./gradlew assemble check

      - name: Fingerprints
        run: ./gradlew checkFingerPrints

      - name: Create release notes
        run: ./gradlew createReleaseNotes

      - name: Create GitHub Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ inputs.tag || github.ref_name }}
          
          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes-file .release-note.md \
            ./wrapper/build/outputs/apk/release/wrapper-release.apk#wwwallet-${TAG}.apk \
            ./wrapper/build/outputs/apk/debug/wrapper-debug.apk#wwwallet-debug-${TAG}.apk
